# Generated by Django 4.2.3 on 2023-07-14 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_todo_blocking_alter_todo_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='blocking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.todo'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.project'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='to_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Assigned date'),
        ),
    ]
