# Generated by Django 4.2.3 on 2023-07-15 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_todo_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='blocking',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='project',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
